spring.application.name=FullStackCrud
spring.datasource.url=jdbc:mysql://localhost:3306/fullstackcrud
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto = update
